---
title: "IMDBData"
author: "GMD"
date: "3/8/2021"
output: html_document
---

#Panggil library
```{r}
library(ggplot2)
library(dplyr)
library(tidyr)
```

##Import Dataset
```{r}
data <- read.csv("IMDB-Movie-Data.csv")
data
data %>%
  filter(Title == "Cars 2")
head(data)
```

##Hitung jumlah film untuk masing-masing genre
```{r}
#Buat genre ke kolom baru (Genre1, Genre2, Genre3)
i <- 1
while (i <= nrow(data)) {
  genres <- unlist(strsplit(data$Genre[i], ",", fixed = TRUE))
  data$Genre1[i] <- genres[1]
  data$Genre2[i] <- genres[2]
  data$Genre3[i] <- genres[3]
  i <- i + 1
}
data
#Buat vector berisi setiap jenis genre
allGenre <- unique(c(data$Genre1, data$Genre2, data$Genre3))
#Hapus nilai NA
allGenre <- allGenre[!is.na(allGenre)]

#Buat dataframe baru untuk menghitung jumlah kemunculan masing-masing genre
genreCount <- data.frame(allGenre, rep(0, 20))
#Beri nama untuk kolom
colnames(genreCount) <- c("genre", "count")

#Hitung kemunculan masing-masing genre, untuk setiap baris di data
m <- 1
while (m <= nrow(data)) {
  n <- 1
  while (n <= nrow(genreCount)) {
    if(grepl(genreCount$genre[n], data$Genre[m], fixed = TRUE)){
      genreCount$count[n] <- genreCount$count[n] + 1
    }
    n <- n + 1
  }
  m <- m + 1
}

genreCount
```

##Jumlah Masing-masing genre per tahun
```{r}
dataGenre1 <- data.frame(data$Title, data$Year, data$Genre1, data$Director, data$Actors, data$Runtime..Minutes., data$Rating, data$Votes, data$Revenue..Millions., data$Metascore)
colnames(dataGenre1) <- c("Title", "Year", "Genre", "Director", "Actors", "Runtime", "Rating", "Votes", "Revenue", "Metascore")
dataGenre1

dataGenre2 <- data.frame(data$Title, data$Year, data$Genre2, data$Director, data$Actors, data$Runtime..Minutes., data$Rating, data$Votes, data$Revenue..Millions., data$Metascore)
colnames(dataGenre2) <- c("Title", "Year", "Genre", "Director", "Actors", "Runtime", "Rating", "Votes", "Revenue", "Metascore")
dataGenre2 <- dataGenre2 %>% drop_na(Genre)
dataGenre2

dataGenre3 <- data.frame(data$Title, data$Year, data$Genre3, data$Director, data$Actors, data$Runtime..Minutes., data$Rating, data$Votes, data$Revenue..Millions., data$Metascore)
colnames(dataGenre3) <- c("Title", "Year", "Genre", "Director", "Actors", "Runtime", "Rating", "Votes", "Revenue", "Metascore")
dataGenre3 <- dataGenre3 %>% drop_na(Genre)
dataGenre3

dataGenre <- bind_rows(dataGenre1, dataGenre2, dataGenre3)
dataGenreYear <- dataGenre %>%
                  group_by(Year, Genre) %>%
                  summarise(Count = n())
dataGenreYear

dataGenre %>% 
  filter(Title == "Guardians of the Galaxy")

ggplot(dataGenreYear, aes(x = as.factor(Year), y = Count, fill = Genre))+
  geom_col(position = "stack")
```

##Dataframe akhir, gabungan dari genre dan aktor
```{r}
j <- 1
while (j <= nrow(dataGenre)) {
  actors <- unlist(strsplit(dataGenre$Actors[j], ",", fixed = TRUE))
  dataGenre$Actor1[j] <- actors[1]
  dataGenre$Actor2[j] <- actors[2]
  dataGenre$Actor3[j] <- actors[3]
  dataGenre$Actor4[j] <- actors[4]
  j <- j + 1
}

dataGenreActor1 <- data.frame(dataGenre$Title, dataGenre$Year, dataGenre$Genre, dataGenre$Director, dataGenre$Actor1, dataGenre$Runtime, dataGenre$Rating, dataGenre$Votes, dataGenre$Revenue, dataGenre$Metascore)
colnames(dataGenreActor1) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")

dataGenreActor2 <- data.frame(dataGenre$Title, dataGenre$Year, dataGenre$Genre, dataGenre$Director, dataGenre$Actor2, dataGenre$Runtime, dataGenre$Rating, dataGenre$Votes, dataGenre$Revenue, dataGenre$Metascore)
colnames(dataGenreActor2) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")

dataGenreActor3 <- data.frame(dataGenre$Title, dataGenre$Year, dataGenre$Genre, dataGenre$Director, dataGenre$Actor3, dataGenre$Runtime, dataGenre$Rating, dataGenre$Votes, dataGenre$Revenue, dataGenre$Metascore)
colnames(dataGenreActor3) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")

dataGenreActor4 <- data.frame(dataGenre$Title, dataGenre$Year, dataGenre$Genre, dataGenre$Director, dataGenre$Actor4, dataGenre$Runtime, dataGenre$Rating, dataGenre$Votes, dataGenre$Revenue, dataGenre$Metascore)
colnames(dataGenreActor4) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")
dataGenreActor4 <- dataGenreActor4 %>% drop_na(Actor)

dataGenreActor <- bind_rows(dataGenreActor1, dataGenreActor2, dataGenreActor3, dataGenreActor4)
dataGenreActor %>%
  filter(Title == "Guardians of the Galaxy")

filmGenreCount <- dataGenreActor %>%
                    group_by(Title) %>%
                    summarise(Count = n_distinct(Genre))
filmGenreCount

mean(filmGenreCount$Count)

actorFilmCount <- dataGenreActor %>%
                    group_by(Actor) %>%
                    summarise(CountFilm = n_distinct(Title))

actorGenreCount <- inner_join(dataGenreActor, actorFilmCount %>%
                                filter(CountFilm > 1), by = "Actor") %>%
                    group_by(Actor) %>%
                    summarise(CountGenre = n_distinct(Genre), CountFilm = n_distinct(Title))

actorGenreCount

ggplot(actorGenreCount, aes(x = as.factor(CountGenre)))+
  geom_bar()+
  xlab("Jumlah genre yang dimainkan")+
  ylab("Banyaknya aktor")

mean(actorGenreCount$CountGenre)

ggplot(actorGenreCount, aes(x = as.factor(CountFilm)))+
  geom_bar()+
  xlab("Jumlah film yang dimainkan")+
  ylab("Banyaknya aktor")

mean(actorGenreCount$CountFilm)

temp <- actorGenreCount$CountGenre/actorGenreCount$CountFilm
temp[temp > 2 & temp < 2.5]

actorGenreCount %>%
  arrange(desc(CountGenre/CountFilm))

hist(temp, main = "Jumlah Genre / Jumlah Film tiap Aktor", xlab = "CountGenre/CountActor")
```

```{r}
dataMaxRev <- dataGenre %>%
  group_by(Genre) %>%
  summarise(Revenue = max(Revenue, na.rm = TRUE))

dataMaxRev
dataGenre
dataMaxRev <- inner_join(dataMaxRev, dataGenre %>%
                           select(Title, Revenue, Genre), by = c("Revenue", "Genre")) 

unique(dataMaxRev)
```


```{r}
data %>%
  group_by(Year, Genre) %>%
  summarise(n())

sum(is.na(data))

data_rating <- data %>%
  group_by(Director) %>%
  summarise(mean = mean(Metascore), count = n(), rev = sum(Revenue..Millions.)) %>%
  filter(count > mean(count)) %>%
  arrange(desc(rev))

data_rating

ggplot(data_rating, aes(x = mean, y = rev))+
  geom_point()
```
```{r}
data2 <- read.csv("IMDB-Movie-Data.csv")
dataMetaRev <- data2 %>% 
                group_by(Director) %>%
                summarise(meta = mean(Metascore), rev = mean(Revenue..Millions.)) %>%
                drop_na(rev) %>%
                arrange(desc(meta))

dataMetaRev

dataMetaRevHigh <- dataMetaRev[1:100,]
dataMetaRevHigh

mean(dataMetaRev$rev)
mean(dataMetaRevHigh$rev)

boxplot(dataMetaRev$rev, dataMetaRevHigh$rev, names = c("Semua", "Metascore tinggi"))
```

```{r}
ggplot(data2, aes(x = Rating, y = Metascore))+
  geom_point()+
  geom_smooth()

metaRatingDiff <- vector(mode = "double", length = nrow(data2))
metaRatingDiff <- metaRatingDiff[!is.na(metaRatingDiff)]


i <- 1
while(i <= nrow(data2)){
  metaRatingDiff[i] <- abs((data2$Metascore[i]/10) - data2$Rating[i])
  i <- i + 1
}

hist(metaRatingDiff, main = "Histogram perbedaan antara Rating (user) dan Metascore", xlab = "Diff")

data2$MetaRatingDiff <- metaRatingDiff

data2 %>%
  filter(MetaRatingDiff > 3.5) %>%
  select(Rank, Title, MetaRatingDiff)
```


```{r}
j <- 1
while (j <= nrow(data)) {
  actors <- unlist(strsplit(data$Actors[j], ",", fixed = TRUE))
  data$Actor1[j] <- actors[1]
  data$Actor2[j] <- actors[2]
  data$Actor3[j] <- actors[3]
  data$Actor4[j] <- actors[4]
  j <- j + 1
}

dataActor1 <- data.frame(data$Title, data$Year, data$Genre, data$Director, data$Actor1, data$Runtime, data$Rating, data$Votes, data$Revenue, data$Metascore)
colnames(dataActor1) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")

dataActor2 <- data.frame(data$Title, data$Year, data$Genre, data$Director, data$Actor2, data$Runtime, data$Rating, data$Votes, data$Revenue, data$Metascore)
colnames(dataActor2) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")

dataActor3 <- data.frame(data$Title, data$Year, data$Genre, data$Director, data$Actor3, data$Runtime, data$Rating, data$Votes, data$Revenue, data$Metascore)
colnames(dataActor3) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")

dataActor4 <- data.frame(data$Title, data$Year, data$Genre, data$Director, data$Actor4, data$Runtime, data$Rating, data$Votes, data$Revenue, data$Metascore)
colnames(dataActor4) <- c("Title", "Year", "Genre", "Director", "Actor", "Runtime", "Rating", "Votes", "Revenue", "Metascore")
dataActor4 <- dataActor4 %>% drop_na(Actor)

dataActor <- bind_rows(dataActor1, dataActor2, dataActor3, dataActor4)

dataActor %>%
  group_by(Director) %>%
  summarise(Count = n_distinct(Title)) %>%
  filter(Count > 1)

dataActorDir <- inner_join(dataActor, dataActor %>%
                                      group_by(Director) %>%
                                      summarise(Count = n_distinct(Title)) %>%
                                      filter(Count > 1), by = "Director")
                
dataActorDir %>%
  filter(Director == "James Gunn")

dataActorDir <- dataActorDir %>%
                  group_by(Director, Actor) %>%
                  summarise(Count = n_distinct(Title)) %>%
                  arrange(desc(Count))

dataActorDir

ggplot(dataActorDir, aes(x = as.factor(Count)))+
  geom_bar()+
  xlab("Berapa kali bekerja bersama")+
  ylab("Jumlah")+
  ggtitle("Banyaknya aktor dan director yang bekerja bersama")

dataActor %>%
  filter(Director == "David Yates")
```
```{r}
remove_outliers <- function(x, na.rm = TRUE, ...) {
  qnt <- quantile(x, probs=c(.25, .75), na.rm = na.rm, ...)
  H <- 1.5 * IQR(x, na.rm = na.rm)
  y <- x
  y[x < (qnt[1] - H)] <- NA
  y[x > (qnt[2] + H)] <- NA
  y
}

remove_outliers(data$Revenue..Millions.)
remove_outliers(data$Votes)

length(data$Votes[!data$Votes %in% boxplot.stats(data$Votes)$out])
length(data$Revenue..Millions.[!data$Revenue..Millions. %in% boxplot.stats(data$Revenue..Millions.)$out])

boxplot(data$Votes, main = "Boxplot Votes")
boxplot(data$Revenue..Millions., main = "Boxplot Revenue")

ggplot(data, aes(x = remove_outliers(Revenue..Millions.), y = remove_outliers(Votes)))+
  geom_point()+
  geom_smooth()+
  xlab("Revenue")+
  ylab("Votes")

data %>%
  select(Revenue..Millions., Votes) %>%
  arrange(Revenue..Millions.)

data
```




